apiVersion: v1
kind: pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: vikramnagarkar/multi-client
      ports:
      - containerPort: 3000
